const rotw = [
  "United States",
  "Canada",
  "Brazil",
  "Iceland",
  "Chile",
  "Peru",
  "Mexico",
  "Panama",
  "Argentina",
  "Colombia",
  "South Africa",
  "Ecuador",
  "Russia",
  "Costa Rica",
  "Chile",
  "Kazakhstan",
  "Venezuela",
  "Uruguay",
  "Senegal",
  "Dominican Republic",
  "Cruise ship (Grand Princess)",
  "Martinique",
  "Burkina Faso",
  "French Guiana",
  "Bolivia",
  "Uzbekistan",
  "Cameroon",
  "Paraguay",
  "Jamaica",
  "Reunion Island",
  "Honduras",
  "Guyana",
  "Rwanda",
  "Channel Islands",
  "Ghana",
  "Guadeloupe Islands",
  "Guatemala",
  "Mongolia",
  "Cuba",
  "Ethiopia",
  "Trinidad and Tobago",
  "Guam",
  "Puerto Rico",
  "Ivory Costa",
  "Kenya",
  "Seychelles",
  "Nigeria",
  "Gibraltar",
  "Saint Barthelemy",
  "Congo (DRC)",
  " French Polynesia",
  "Martinique",
  "Aruba",
  "curacao",
  "Saint Martin",
  "Morocco",
  "Barbados",
  "Liberia",
  "Namibia",
  "Togo",
  "Cayman Islands",
  "Gabon",
  "Guinea",
  "Saint Vincent",
  "Somalia",
  "Antigua",
  "Bahamas",
  "Greenland",
  "Congo",
  "Tanzania"
];

module.exports = rotw;
